const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const sockets = [];
const sleep = ms => new Promise(r => setTimeout(r, ms));
async function connect(url) {
  const ws = new WebSocket(url); sockets.push(ws);
  await new Promise((resolve, reject) => { ws.addEventListener('open', resolve, {once:true}); ws.addEventListener('error', reject, {once:true}); });
  let seq=0; const pending=new Map();
  ws.addEventListener('message', e => { const m=JSON.parse(e.data); if(m.id && pending.has(m.id)) { const [resolve,reject,timer]=pending.get(m.id); clearTimeout(timer); pending.delete(m.id); m.error?reject(Error(JSON.stringify(m.error))):resolve(m.result); } });
  return (method, params={}) => new Promise((resolve,reject) => { const id=++seq; const timer=setTimeout(()=>{pending.delete(id);reject(Error('Tempo esgotado: '+method));},20000);pending.set(id,[resolve,reject,timer]);ws.send(JSON.stringify({id,method,params})); });
}
function assert(ok,msg){if(!ok)throw Error(msg);console.log('OK: '+msg);}
(async()=>{
  const targets = await (await fetch('http://127.0.0.1:9222/json')).json();
  const tab=targets.find(t=>t.type==='page'),call=await connect(tab.webSocketDebuggerUrl);
  await call('Page.enable');
  await call('Runtime.enable');
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text+' '+(r.exceptionDetails.exception?.description||''));return r.result.value;};
  const navigate=async file=>{await call('Page.navigate',{url:'file:///'+path.join(root,file).replaceAll('\\','/')});for(let i=0;i<50;i++){if(await evaluate('document.readyState === "complete"'))break;await sleep(100);}await sleep(150);};
  const date=async s=>{await evaluate(`document.getElementById('date').value=${JSON.stringify(s)};document.getElementById('date').dispatchEvent(new Event('change',{bubbles:true}));`);};
  await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
  await navigate('index.html');
  await evaluate('localStorage.removeItem("zedoacai-cronograma-v1")');
  await navigate('index.html');
  assert(await evaluate('tasks.length')===25,'Todas as 25 tarefas estão presentes no painel');
  assert(await evaluate('source.tarefas.every(t=>!/[ÃÂ]/.test(t.tarefa))'),'Textos das tarefas preservam acentos');
  for(const [s,n] of [['2026-10-01',19],['2026-10-02',18],['2026-10-03',15],['2026-10-08',20],['2026-10-15',17],['2026-10-22',20],['2026-10-29',17],['2026-10-31',13],['2026-11-01',15],['2027-02-28',16]]) {
    await date(s);assert(await evaluate('document.querySelectorAll("[data-check]").length')===n,`${s} mostra ${n} tarefas conforme as frequências`);
  }
  await date('2026-10-01');
  await evaluate('document.querySelector("[data-owner=MEN-S1-001]").value="Ana";document.querySelector("[data-owner=MEN-S1-001]").dispatchEvent(new Event("change",{bubbles:true}));document.querySelector("[data-check=MEN-S1-001]").click();');
  await date('2026-10-03');
  assert(await evaluate('document.querySelector("[data-check=MEN-S1-001]").checked'),'Conclusão mensal compartilhada entre os dias do mesmo período');
  await date('2026-11-01');
  assert(!await evaluate('document.querySelector("[data-check=MEN-S1-001]").checked'),'Novo mês inicia nova ocorrência mensal');
  await date('2026-10-08');
  await evaluate('document.querySelector("[data-check=QUI-S24-001]").click();');
  await date('2026-10-14');
  assert(await evaluate('document.querySelector("[data-check=QUI-S24-001]").checked'),'Conclusão quinzenal permanece durante a segunda semana');
  await date('2026-10-22');
  assert(!await evaluate('document.querySelector("[data-check=QUI-S24-001]").checked'),'Quarta semana cria nova ocorrência quinzenal');
  await date('2026-10-01');
  await evaluate('document.querySelector("[data-check=DIA-FEC-001]").click();document.querySelector("[data-check=DIA-FEC-002]").click();');
  assert(!await evaluate('document.querySelector(".closing-state").classList.contains("ready")'),'Fechamento permanece pendente enquanto lixo e lixeiras não foram conferidos');
  await evaluate('document.querySelector("[data-check=DIA-FEC-003]").click();');
  assert(await evaluate('document.querySelector(".closing-state").classList.contains("ready")'),'Fechamento muda de status após as três conferências');
  assert(await evaluate('document.querySelector(".stats .stat:last-child strong").textContent')==='01','Cuidado contínuo crítico permanece pendente');
  await navigate('index.html');
  await date('2026-10-01');
  assert(await evaluate('document.querySelector("[data-check=MEN-S1-001]").checked && document.querySelector("[data-owner=MEN-S1-001]").value === "Ana"'),'Responsável e conclusão persistem após recarregar');
  await evaluate('document.querySelector("[data-view=history]").click()');
  assert(await evaluate('document.querySelectorAll("tbody tr").length')===5,'Histórico reúne as cinco ocorrências concluídas');
  await evaluate('document.querySelector("[data-view=month]").click()');
  assert(await evaluate('document.querySelectorAll(".monthcard").length')===5,'Mês com 31 dias mostra cinco períodos');
  await date('2027-02-01');
  assert(await evaluate('document.querySelectorAll(".monthcard").length')===4,'Fevereiro com 28 dias mostra quatro períodos');
  await date('2026-10-01');
  await evaluate('document.querySelector("[data-view=week]").click()');
  assert(await evaluate('document.querySelectorAll(".daycard").length')===7,'Visão semanal mostra os sete dias');
  await evaluate('document.querySelector("[data-day=\\"2026-10-02\\"]").click()');
  assert(await evaluate('document.getElementById("date").value')==='2026-10-02','Cartão semanal abre a data correta no checklist');
  await evaluate('document.querySelector("[data-filter=critical]").click()');
  assert(await evaluate('document.querySelectorAll("[data-check]").length')===3,'Filtro Críticas mostra os três cuidados críticos');
  await evaluate('document.querySelector("[data-filter=all]").click()');
  await evaluate('localStorage.removeItem("zedoacai-cronograma-v1")');
  await navigate('index.html');
  await date('2026-10-01');
  assert(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),'Painel sem rolagem horizontal no computador');
  let shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});
  fs.writeFileSync(path.join(root,'previa_painel.png'),Buffer.from(shot.data,'base64'));
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),'Painel se adapta a uma tela de celular de 390 px');
  shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});
  fs.writeFileSync(path.join(root,'previa_celular.png'),Buffer.from(shot.data,'base64'));
  await call('Emulation.setDeviceMetricsOverride',{width:1100,height:1200,deviceScaleFactor:1,mobile:false});
  await navigate('cronograma_para_imprimir.html');
  assert(await evaluate('document.querySelectorAll("[data-task]").length')===25,'Impressão contém as 25 tarefas');
  const originalTasks=JSON.parse(fs.readFileSync(path.join(root,'cronograma_loja.json'),'utf8')).tarefas;
  assert(await evaluate(`${JSON.stringify(originalTasks.map(t=>t.tarefa))}.every(text=>Array.from(document.querySelectorAll('.tasktext')).some(el=>el.textContent.trim().startsWith(text)))`),'Versão impressa preserva exatamente o texto de todas as tarefas');
  assert(await evaluate('Array.from(document.querySelectorAll(".page,.block")).every(p=>p.scrollHeight<=p.clientHeight+1)'),'Conteúdo cabe nas duas páginas A4 e nos blocos sem corte');
  const pdf=await call('Page.printToPDF',{printBackground:true,paperWidth:8.2677165354,paperHeight:11.692913386,marginTop:0,marginBottom:0,marginLeft:0,marginRight:0,preferCSSPageSize:true});
  const pdfBuffer=Buffer.from(pdf.data,'base64');fs.writeFileSync(path.join(root,'cronograma_para_imprimir.pdf'),pdfBuffer);
  const pageCount=(pdfBuffer.toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length;
  assert(pageCount===2,'PDF gerado com exatamente duas páginas');
  const poster=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(root,'previa_impressao.png'),Buffer.from(poster.data,'base64'));
  fs.writeFileSync(path.join(root,'resultado_verificacao.txt'),'Verificação concluída: 25 tarefas preservadas; frequências corretas; conclusão por período; persistência; histórico; filtros; computador e celular sem rolagem horizontal; PDF A4 em duas páginas.\n','utf8');
  console.log('ARQUIVOS GERADOS: PDF e prévias.');
  sockets.forEach(s=>s.close());
})().catch(e=>{console.error(e.stack);sockets.forEach(s=>s.close());process.exitCode=1;});
